### ISSUE TITLE
0.6.0 Docs Update

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/contour#644]
There have been a number of modifications/removals/changes to our original planned IngressRoute design spec, examples, and docs leading up to 0.6.  This is a tracking issue for needed docs & example updates to ensure consistency across the project.

- [x] Virtual Host Aliases were removed from the spec (#652)
- [x] Add example using multiple IR to work around removed Aliases feature (#649)
- [x] TLS & permitInsecure (#652)

README.md
- [x] Second paragraph should expand on why we created IR and then point to IngressRoute documentation. (#659)
- [x] “This is an early release” — Remove! (#659)
- [x] Update design/roadmap.md file (#658)
- [x] Contour Kubernetes version still 1.7? (#659)
- [x] “See also the k8s documentation for Services & Ingress” (#659)
- [x] Add ZenHub contributor section (steal from Ark) (#659)

Docs/README.md
- [x] Move IngressRoute API link to under “Deployment Options” (#659)
- [x] Should Deployment Options have an “Advanced Deployment” where contour & envoy are not in the same Pod? (#659)

Docs/annotations.md
- [x] We should link to the IngressRoute doc form the top level and comment that Ingress annotations are eliminated by using IngressRoute API.  Service annotations still apply (PR #655)

Docs/prometheus.md
- [x] Is this still accurate? Especially the admin socket public? (PR #654)

Docs/minikube.md
- [x] Update minikube (‘qinikube-example’???) Kuard example to be IngressRoute.  (PR #660)

docs/about.md
- [x] Update to include translating IngressRoute objects (#666)
- [x] Update to include how Ingress -> DAG -> CDS/SDS/RDS (#666)

troubleshooting.md
- [x] Update https://github.com/heptio/contour/blob/master/docs/troubleshooting.md#cant-make-kube-lego-work-with-contour (#PR 656)
- [x] Should we have a doc for making DOT notation output of DAG? (PR #656)

Docs/deploy-options.md
- [x] kuard example should use IngressRoute https://github.com/heptio/contour/blob/master/docs/deploy-options.md#test (PR #664)

Docs/faq.md
- [x] Idea: “Ingress” or “IngressRoute”? In FAQ (PR #657)

**Comment by rosskukulinski** [comment]
I haven't done a consistency review, but anything else that jumps to mind @davecheney @stevesloka @alexbrand?

cc: @Bradamant3

**Comment by alexbrand** [comment]
We need to remove aliases not only from docs, but also from the CRD printer/formatter thingy that shows them when you do `kubectl get ingressroute`. Just thought I would add a note here so that it doesn't slip through the cracks.

**Comment by rosskukulinski** [comment]
I reviewed all existing documentation and updated the issue description to highlight other locations that need to be reworked.  cc: @davecheney @alexbrand @stevesloka

**Comment by alexbrand** [comment]
About:
> Docs/deploy-options.md
>  kuard example should use IngressRoute > https://github.com/heptio/contour/blob/master/docs/deploy-options.md#test

The example that uses the Ingress resource does not have any host matching rules, which makes it very easy from a user-perspective to open up a browser and validate Contour is working. 

We cannot support a similar workflow using IngressRoutes, given that we don't yet support wildcard host matching rules. If we were to update the docs to use IngressRoute, we would need to suggest a browser plugin for setting the Host header 👎 , or suggest the use of `curl` over opening a browser.

I think my vote goes toward replacing the browser for a `curl` command, but wanted to get other thoughts.

**Comment by stevesloka** [comment]
I still think we should document both Ingress & IngressRoute. Ingress is still widely used today and Contour is not dropping support for it. 

Using curl to demonstrate is fine (in addition to docs on how to set up real fqdn).

**Comment by alexbrand** [comment]
Thanks @stevesloka. Will open a PR that adds IngressRoute to the deploy-options.md.

**Comment by rosskukulinski** [comment]
Looks like all docs are in place.  

Created #687 to track the docs website update.
